name: Run Lint and Tests

on:
    pull_request:
        branches:
            - main
            - alpha
            - beta
            - next

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [lts/-1, lts/*]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: npm install

      - name: npm lint
        run: npm run lint

      - name: npm types
        run: npm run types

      - name: npm test
        run: npm test
